### PR TITLE
Add scope inheritance for debounce utility function

### PR DESCRIPTION
**Pull request by ilyasfoo**
## Improved

Added support for scope inheritance for `debounce` utility function.

### Use case example

Wrap component method with debounce and accessing component's local value. Previously `this` context would be `undefined`.
```javascript
export default {
  data() {
    return {
      localData: "Not yet"
    };
  },
  methods: {
    debounceTest: debounce(function() {
      this.localData = "Changed by debounce";
    })
  },
  mounted() {
    this.debounceTest()
  }
}
```

### CODE REVIEW

**Comment by dhershman1** [comment]
Please just pass an arrow function to debounce instead.

your test example:

```js
test('Inherits parent scope', t => {
  const runner = function (val) {
    const someclass = function () {
      this.somevalue = ''
      this.somefunction = debounce(() => {
        t.ok(val)
        t.same(this.somevalue, 'testing')
        t.end()
      })
    }

    const instance = new someclass
    instance.somevalue = val
    instance.somefunction()
  }

  runner('testing')
})
```

This works with current debounce.

**Comment by ilyasfoo** [comment]
Sorry, the test case wasn't reflecting the issue with Vue. I have updated the test case with actual codes from Vue class.

This is an example that doesn't work with current debounce: 

https://codesandbox.io/s/debounce-test-yjhus

**Comment by dhershman1** [comment]
Sorry this took so long to get back too, been a pretty busy week, and was contemplating this as I hate having to use this and pass it along like that. 

Alas, this is the world we live in with javascript.

**Comment by ilyasfoo** [comment]
No worries, I have changed to development branch but comes along with other unmerged commits from master, if you don't mind.

**Comment by dhershman1** [comment]
Merged and added to master with PR #31 and has been deployed to npm with version 2.5.2, thanks for the PR!

**Pull request merged**
